import placeholderImg from "/placeholder.svg";

export const PLACEHOLDERS = {
  WEBSITE_NAME: "{{WEBSITE_NAME}}",
  TAGLINE: "{{TAGLINE}}",

  LOGO_IMAGE_ALT: "{{LOGO_IMAGE}}",

  HERO_TITLE: "{{HERO_TITLE}}",
  HERO_SUBTITLE: "{{HERO_SUBTITLE}}",
  CTA_TEXT_1: "{{CTA_TEXT_1}}",
  CTA_TEXT_2: "{{CTA_TEXT_2}}",

  NAV_MENU_LABELS: "{{NAV_MENU_LABELS}}",

  NAV_MORE_TRIGGER: "{{NAV_MENU_LABELS}}",
  NAV_MORE_LABELS: "{{NAV_MENU_LABELS}}",

  EVENT_TITLE_1: "{{EVENT_TITLE_1}}",
  EVENT_TITLE_2: "{{EVENT_TITLE_2}}",
  EVENT_TITLE_3: "{{EVENT_TITLE_3}}",
  EVENT_IMAGE_ALT_1: "{{EVENT_IMAGE_1}}",
  EVENT_IMAGE_ALT_2: "{{EVENT_IMAGE_2}}",
  EVENT_IMAGE_ALT_3: "{{EVENT_IMAGE_3}}",

  HERO_IMAGE_ALT: "{{EVENT_IMAGE_1}}",

  SECTION_TEXT_CONTENT: "{{SECTION_TEXT_CONTENT}}",

  CONTACT_EMAIL: "{{CONTACT_EMAIL}}",
  CONTACT_PHONE: "{{CONTACT_PHONE}}",
  ADDRESS: "{{ADDRESS}}",
} as const;

export const PLACEHOLDER_CONTENT = {
  WEBSITE_NAME: PLACEHOLDERS.WEBSITE_NAME,
  TAGLINE: PLACEHOLDERS.TAGLINE,

  LOGO_IMAGE_SRC: placeholderImg,
  LOGO_IMAGE_ALT: PLACEHOLDERS.LOGO_IMAGE_ALT,

  HERO_TITLE: PLACEHOLDERS.HERO_TITLE,
  HERO_SUBTITLE: PLACEHOLDERS.HERO_SUBTITLE,
  CTA_TEXT_1: PLACEHOLDERS.CTA_TEXT_1,
  CTA_TEXT_2: PLACEHOLDERS.CTA_TEXT_2,

  NAV_MENU_LABELS: new Array(7).fill(PLACEHOLDERS.NAV_MENU_LABELS),
  NAV_MORE_LABELS: new Array(3).fill(PLACEHOLDERS.NAV_MENU_LABELS),
  NAV_MORE_TRIGGER: PLACEHOLDERS.NAV_MENU_LABELS,

  HERO_IMAGE_SRC: placeholderImg,
  EVENT_IMAGE_SRC_1: placeholderImg,
  EVENT_IMAGE_SRC_2: placeholderImg,
  EVENT_IMAGE_SRC_3: placeholderImg,

  EVENT_TITLE_1: PLACEHOLDERS.EVENT_TITLE_1,
  EVENT_TITLE_2: PLACEHOLDERS.EVENT_TITLE_2,
  EVENT_TITLE_3: PLACEHOLDERS.EVENT_TITLE_3,

  SECTION_TEXT_CONTENT: PLACEHOLDERS.SECTION_TEXT_CONTENT,

  CONTACT_EMAIL: PLACEHOLDERS.CONTACT_EMAIL,
  CONTACT_PHONE: PLACEHOLDERS.CONTACT_PHONE,
  ADDRESS: PLACEHOLDERS.ADDRESS,
} as const;

