export const PLACEHOLDERS = {
  WEBSITE_NAME: "{{WEBSITE_NAME}}",
  TAGLINE: "{{TAGLINE}}",

  LOGO_IMAGE_ALT: "{{LOGO_IMAGE}}",

  HERO_TITLE: "{{HERO_TITLE}}",
  HERO_SUBTITLE: "{{HERO_SUBTITLE}}",
  CTA_TEXT_1: "{{CTA_TEXT_1}}",
  CTA_TEXT_2: "{{CTA_TEXT_2}}",

  NAV_MENU_LABELS: "{{NAV_MENU_LABELS}}",

  EVENT_TITLE_1: "{{EVENT_TITLE_1}}",
  EVENT_TITLE_2: "{{EVENT_TITLE_2}}",
  EVENT_TITLE_3: "{{EVENT_TITLE_3}}",
  EVENT_IMAGE_ALT_1: "{{EVENT_IMAGE_1}}",
  EVENT_IMAGE_ALT_2: "{{EVENT_IMAGE_2}}",
  EVENT_IMAGE_ALT_3: "{{EVENT_IMAGE_3}}",

  SECTION_TEXT_CONTENT: "{{SECTION_TEXT_CONTENT}}",

  CONTACT_EMAIL: "{{CONTACT_EMAIL}}",
  CONTACT_PHONE: "{{CONTACT_PHONE}}",
  ADDRESS: "{{ADDRESS}}",
} as const;
